// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (c) 2026 Götz Kohlberg. All rights reserved.
// Dual licensed: AGPL-3.0 + SIDJUA Commercial License. See LICENSE.

import type { ReportData, ReportSection, ReportTable, ChartImage } from "./types.js";

// ─── Public entry point ───────────────────────────────────────────────────────

/** Render a complete, self-contained HTML document from ReportData. */
export function renderReportHtml(data: ReportData): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <style>
    body { font-family: 'Segoe UI', Arial, sans-serif; margin: 40px; color: #333; line-height: 1.6; }
    h1 { color: #1a1a2e; border-bottom: 3px solid #16213e; padding-bottom: 10px; }
    h2 { color: #16213e; margin-top: 30px; }
    .meta { color: #666; font-size: 0.9em; margin-bottom: 30px; }
    .summary-box { background: #f0f4f8; border-left: 4px solid #16213e; padding: 15px 20px; margin: 20px 0; }
    table { width: 100%; border-collapse: collapse; margin: 15px 0; }
    th { background: #16213e; color: white; padding: 10px 15px; text-align: left; }
    td { padding: 8px 15px; border-bottom: 1px solid #e0e0e0; }
    tr:nth-child(even) { background: #f8f9fa; }
    .chart-container { margin: 20px 0; text-align: center; }
    .chart-container img { max-width: 100%; border: 1px solid #e0e0e0; border-radius: 4px; }
    .chart-title { font-size: 0.85em; color: #666; margin-top: 5px; }
    .recommendation { background: #fff3cd; border-left: 4px solid #ffc107; padding: 10px 15px; margin: 10px 0; }
    .footer { margin-top: 40px; padding-top: 15px; border-top: 1px solid #ccc; font-size: 0.8em; color: #999; }
    @media print { body { margin: 20px; } }
  </style>
</head>
<body>
  <h1>${escapeHtml(data.title)}</h1>
  <div class="meta">
    Period: ${formatDate(data.period.from)} &mdash; ${formatDate(data.period.to)}<br>
    Generated: ${formatDateTime(data.generatedAt)} by ${escapeHtml(data.generatedBy)}
  </div>
  ${data.sections.map(renderSection).join("\n")}
  <div class="footer">
    Generated by SIDJUA &mdash; Governed AI Agent Platform
  </div>
</body>
</html>`;
}

// ─── Section renderer ─────────────────────────────────────────────────────────

function renderSection(section: ReportSection): string {
  const parts: string[] = [];
  parts.push(`  <section>`);
  parts.push(`    <h2>${escapeHtml(section.heading)}</h2>`);
  if (section.content) {
    parts.push(`    <div class="section-content">${section.content}</div>`);
  }
  if (section.charts !== undefined && section.charts.length > 0) {
    for (const chart of section.charts) {
      parts.push(renderChart(chart));
    }
  }
  if (section.table !== undefined) {
    parts.push(renderTable(section.table));
  }
  parts.push(`  </section>`);
  return parts.join("\n");
}

// ─── Table renderer ───────────────────────────────────────────────────────────

function renderTable(table: ReportTable): string {
  const headerCells = table.headers
    .map((h) => `<th>${escapeHtml(h)}</th>`)
    .join("");

  const bodyRows = table.rows
    .map((row) => {
      const cells = row.map((cell) => `<td>${escapeHtml(cell)}</td>`).join("");
      return `<tr>${cells}</tr>`;
    })
    .join("\n");

  return `    <table>
      <thead><tr>${headerCells}</tr></thead>
      <tbody>${bodyRows}</tbody>
    </table>`;
}

// ─── Chart renderer ───────────────────────────────────────────────────────────

function renderChart(chart: ChartImage): string {
  const widthAttr  = chart.width  !== undefined ? ` width="${chart.width}"`  : "";
  const heightAttr = chart.height !== undefined ? ` height="${chart.height}"` : "";
  return `    <div class="chart-container">
      <img src="${escapeHtml(chart.src)}" alt="${escapeHtml(chart.alt)}"${widthAttr}${heightAttr}>
      <div class="chart-title">${escapeHtml(chart.title)}</div>
    </div>`;
}

// ─── HTML helpers ─────────────────────────────────────────────────────────────

/** Escape characters that have special meaning in HTML. */
export function escapeHtml(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function formatDate(d: Date): string {
  return d.toISOString().slice(0, 10);  // YYYY-MM-DD
}

function formatDateTime(d: Date): string {
  return d.toISOString().replace("T", " ").slice(0, 19) + " UTC";
}
